package main;
public enum Terminal {
	// KEYWORDS
	ABSTRACT, ASSERT, BOOLEAN, BREAK, BYTE, CASE, CATCH, CHAR, CLASS, CONST, CONTINUE, DEFAULT, DO, DOUBLE, ELSE, ENUM,
	EXTENDS, FINAL, FINALLY, FLOAT, FOR, GOTO, IF, IMPLEMENTS, IMPORT, INSTANCEOF, INT, INTERFACE, LONG, NATIVE, NEW,
	PACKAGE, PRIVATE, PROTECTED, PUBLIC, RETURN, SHORT, STATIC, STRICTFP, SUPER, SWITCH, SYNCHRONIZED, THIS, THROW,
	THROWS, TRANSIENT, TRY, VOID, VOLATILE, WHILE,

	// BOOLEAN LITERALS
	TRUE_LITERAL, FALSE_LITERAL,

	// NULL LITERAL
	NULL_LITERAL,

	// SEPARATORS
	OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_BRACE, CLOSE_BRACE, OPEN_BRACKET, CLOSE_BRACKET, SEMICOLON, COMMA, DOT,
	ELLIPSES, AT_SYMBOL, DOUBLE_COLON,

	// OPERATORS
	ASSIGN, LESS_THAN, GREATER_THAN, NOT, BITWISE_COMPLEMENT, TERNARY, COLON, LAMBDA, EQUAL_TO,
	GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO, NOT_EQUAL_TO, AND_GATE, OR_GATE, INCREMENT, DECREMENT, ADD,
	SUBTRACT, MULTIPLY, DIVIDE, AND, OR, XOR, MODULO, LEFT_SHIFT, RIGHT_SHIFT, UNSIGNED_RIGHT_SHIFT, ASSIGN_ADD,
	ASSIGN_SUBTRACT, ASSIGN_MULTIPLY, ASSIGN_DIVIDE, ASSIGN_AND, ASSIGN_OR, ASSIGN_XOR, ASSIGN_MOD, ASSIGN_LEFT_SHIFT,
	ASSIGN_RIGHT_SHIFT, ASSIGN_UNSIGNED_RIGHT_SHIFT,

	// OTHER
	IDENTIFIER, INTEGER_LITERAL, FLOATING_POINT_LITERAL, STRING_LITERAL, CHARACTER_LITERAL,

	// DEPRECATED
	@Deprecated CHARACTER_MARKER,
	@Deprecated STRING_MARKER,
	@Deprecated LINE_COMMENT,
	@Deprecated BLOCK_COMMENT_START,
	@Deprecated BLOCK_COMMENT_END,
}