package main;
public enum Terminal {
	/* ==================== *
	 *       LITERALS       *
	 * ==================== */
	TRUE, FALSE, NULL,


	/* ==================== *
	 *       KEYWORDS       *
	 * ==================== */
	ABSTRACT, ASSERT, BOOLEAN, BREAK, BYTE, CASE, CATCH, CHAR, CLASS, CONST, CONTINUE, DEFAULT, DO, DOUBLE, ELSE, ENUM,
	EXTENDS, FINAL, FINALLY, FLOAT, FOR, GOTO, IF, IMPLEMENTS, IMPORT, INSTANCEOF, INT, INTERFACE, LONG, NATIVE, NEW,
	PACKAGE, PRIVATE, PROTECTED, PUBLIC, RETURN, SHORT, STATIC, STRICTFP, SUPER, SWITCH, SYNCHRONIZED, THIS, THROW,
	THROWS, TRANSIENT, TRY, VOID, VOLATILE, WHILE,


	/* =================== *
	 *      OPERATORS      *
	 * =================== */
	EQUAL_TO, LESS_THAN_OR_EQUAL_TO, GREATER_THAN_OR_EQUAL_TO, NOT_EQUAL_TO, AND_GATE, OR_GATE, INCREMENT, DECREMENT,
	ASSIGN, LESS_THAN, GREATER_THAN, NOT, BITWISE_COMPLEMENT, TERNARY, COLON, LAMBDA, ADD, SUBTRACT, MULTIPLY, DIVIDE,
	AND, OR, XOR, MODULO, LEFT_SHIFT, RIGHT_SHIFT, UNSIGNED_RIGHT_SHIFT, ASSIGN_ADD, ASSIGN_SUBTRACT, ASSIGN_MULTIPLY,
	ASSIGN_DIVIDE, ASSIGN_AND, ASSIGN_OR, ASSIGN_XOR, ASSIGN_MOD, ASSIGN_LEFT_SHIFT, ASSIGN_RIGHT_SHIFT,
	ASSIGN_UNSIGNED_RIGHT_SHIFT,

	/* ==================== *
	 *      SEPARATORS      *
	 * ==================== */
	OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_BRACE, CLOSE_BRACE, OPEN_BRACKET, CLOSE_BRACKET, SEMICOLON, COMMA, DOT,
	ELLIPSES, AT_SYMBOL, DOUBLE_COLON,


	/* =================== *
	 *        OTHER        *
	 * =================== */
	IDENTIFIER,
	CHARACTER_LITERAL, FLOATING_POINT_LITERAL, INTEGER_LITERAL, STRING_LITERAL,


	CHARACTER_MARKER, STRING_MARKER,
	LINE_COMMENT, BLOCK_COMMENT_START, BLOCK_COMMENT_END,
}