package main;
public enum TokenType {
//	OPERATOR, NUMERIC_LITERAL, STRING_LITERAL, CHARACTER_LITERAL, KEYWORD, IDENTIFIER, BRACKET, SEMICOLON,

	@Deprecated SEMICOLON,
	@Deprecated BRACKET,
	@Deprecated NUMERIC_LITERAL,


	IDENTIFIER, KEYWORD, INTEGER_LITERAL, FLOATING_POINT_LITERAL, BOOLEAN_LITERAL, CHARACTER_LITERAL, STRING_LITERAL,
	NULL_LITERAL, SEPARATOR, OPERATOR,
}